#!/usr/bin/env python

import os
import time
import sys
import hashlib

from simperium import core
from simperium import optfunc

TOKENFILE = os.environ.get('HOME')+'/'+'.simplestat'

# You can find you APPID and APIKEY in your app's dashboard
APPID = 'SIMPERIUM_APP_ID'
APIKEY = 'SIMPERIUM_API_KEY'

def get_api():
    if not os.path.exists(TOKENFILE):
        print 'first run: %s init' % sys.argv[0]
        sys.exit(1)
    return core.Api(APPID, open(TOKENFILE).read())


def str_to_id(s):
    m = hashlib.md5()
    m.update(s)
    return m.hexdigest()


def init(username, password):
    auth = core.Auth(APPID, APIKEY)
    token = auth.create(username, password)
    if not token:
        token = auth.authorize(username, password)
    open(TOKENFILE, 'w').write(token)
    os.chmod(TOKENFILE, 0600)
    print 'Welcome %s' % username


def push(dashboard, rest_=['-']):
    dashboard_id = str_to_id(dashboard)
    if not rest_:
        rest_ = sys.stdin.read()[:-1].split()
    to_post = []
    try:
        for arg in rest_:
            key, value = arg.split('=')
            value = int(value)
            to_post.append({
                'dashboard': dashboard_id,
                'name': key,
                'value': value,
                'timeStamp': time.time(),})
    except Exception, e:
        print e
        print "stats should be in the format:"
        print "\tkey=value key=value ..."

    api = get_api()
    api.dashboard.post(dashboard_id, {'name': dashboard, 'timeStamp': time.time()})
    for stat in to_post:
        api.stat.post(dashboard_id+'-'+str_to_id(stat['name']), stat)


def remove(dashboard):
    dashboard_id = str_to_id(dashboard)
    api = get_api()
    for stat in api.stat.index(data=True)['index']:
        if stat['d']['dashboard'] == dashboard_id:
            api.stat.delete(stat['id'])
    api.dashboard.delete(dashboard_id)


def list():
    api = get_api()
    for dashboard in api.dashboard.index(data=True)['index']:
        print dashboard['d']['name']


optfunc.main([init, list, remove, push])
