#!/usr/bin/env python

from simperium import optfunc
from simperium import core
from simperium import changes


class Counter(changes.ChangeProcessor):
    def __init__(self):
        self.count = 0

    def on_change_done(self, value):
        if value: self.count += 1
        else: self.count -= 1


def main(appname, admin_key, bucket):
    api = core.Api(appname, admin_key)
    counter = Counter()
    cv = None
    try:
        while True:
            changes = api[bucket].all(cv, data=True)
            for change in changes:
                counter.process(change)
                print "total todos done: %s" % counter.count
                cv = change['cv']
    except KeyboardInterrupt:
        pass

optfunc.main(main)
