#!/usr/bin/env python

import uuid
import time

from simperium import optfunc
from simperium import core


def list(appname, token):
    api = core.Api(appname, token)
    for item in api.todo.index(data=True)['index']:
        if not item['d'].get('done'):
            print "%-40s%s" % (item['id'], item['d']['text'])


def add(appname, token, text):
    api = core.Api(appname, token)
    api.todo.new({
        'text': text,
        'timeStamp': time.time(),
        'done': False, })


def done(appname, token, todo_id):
    api = core.Api(appname, token)
    api.todo.post(todo_id, {'done': True})


optfunc.main([list, add, done])
