#!/usr/bin/env python
import os
from simperium import optfunc
from simperium import core

def main(appname, admin_key, bucket):
    api = core.Api(appname, admin_key)
    cv = None
    numTodos = 0
    try:
        while True:
            changes = api[bucket].all(cv, data=True)
            for change in changes:
                print str(change) + '\n---'
                cv = change['cv']
    except KeyboardInterrupt:
        pass

optfunc.main(main)
