#!/usr/bin/env python
import os

import pymongo

from simperium import optfunc
from simperium import core

mongohq_url = os.environ['MONGOHQ_URL']
db = pymongo.Connection(mongohq_url)[mongohq_url.split('/')[-1]]

def main(appname, admin_key, bucket):
    api = core.Api(appname, admin_key)
    cv = db['__meta__'].find_one('cv')
    if cv:
        cv = cv['cv']

    try:
        while True:
            changes = api[bucket].all(cv, data=True)
            for change in changes:
                data = change['d']
                print change['d']

                # update mongo with the latest version of the data
                if data:
                    data['_id'] = change['id']
                    db[bucket].save(data)
                else:
                    db[bucket].remove(change['id'])

                # persist the cv to mongo, so changes don't need to be
                # re-processed after restart
                db['__meta__'].save({'_id': 'cv', 'cv': change['cv']})
                cv = change['cv']

    except KeyboardInterrupt:
        pass

optfunc.main(main)
